---
#####################
# Main source code
#####################
- name: Checkout AH Bot module
  git:
    repo: "{{ ahbot_git }}"
    dest: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/{{ azerothcore_source }}/modules/mod-ah-bot"
    version: "{{ ahbot_branch }}"
    force: "{{ azerothcore_git_force }}"
  become_user: "{{ azerothcore_user }}"

# - name: Checkout Autobalance module
#   git:
#     repo: "{{ autobalance_git }}"
#     dest: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/{{ azerothcore_source }}/modules/mod-autobalance"
#     version: "{{ autobalance_branch }}"
#     force: "{{ azerothcore_git_force }}"
#   become_user: "{{ azerothcore_user }}"

- name: Checkout Eluna module
  git:
    repo: "{{ eluna_git }}"
    dest: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/{{ azerothcore_source }}/modules/mod-eluna"
    version: "{{ eluna_branch }}"
    force: "{{ azerothcore_git_force }}"
  become_user: "{{ azerothcore_user }}"

- name: Checkout Individual Progression module
  git:
    repo: "{{ ipp_git }}"
    dest: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/{{ azerothcore_source }}/modules/mod-individual-progression"
    version: "{{ ipp_branch }}"
    force: "{{ azerothcore_git_force }}"
    depth: "1"
  become_user: "{{ azerothcore_user }}"

- name: Checkout Transmog module
  git:
    repo: "{{ transmog_git }}"
    dest: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/{{ azerothcore_source }}/modules/mod-transmog"
    version: "{{ transmog_branch }}"
    force: "{{ azerothcore_git_force }}"
  become_user: "{{ azerothcore_user }}"

- name: Checkout Guildhouse module
  git:
    repo: "{{ guildhouse_git }}"
    dest: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/{{ azerothcore_source }}/modules/mod-guildhouse"
    version: "{{ guildhouse_branch }}"
    force: "{{ azerothcore_git_force }}"
  become_user: "{{ azerothcore_user }}"

- name: Checkout Reagent Bank module
  git:
    repo: "{{ reagentbank_git }}"
    dest: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/{{ azerothcore_source }}/modules/mod-reagent-bank"
    version: "{{ reagentbank_branch }}"
    force: "{{ azerothcore_git_force }}"
  become_user: "{{ azerothcore_user }}"

- name: Checkout Schulte Core module
  git:
    repo: "{{ schultecore_git }}"
    dest: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/{{ azerothcore_source }}/modules/mod-schulte-core"
    version: "{{ schultecore_branch }}"
    force: "{{ azerothcore_git_force }}"
  become_user: "{{ azerothcore_user }}"