---
- name: Check if map data exists
  stat:
    path: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/data/{{ azerothcore_data_version }}"
  register: data_folder

- name: Create data folder
  file:
    path: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/data/{{ azerothcore_data_version }}"
    mode: "0755"
    state: "directory"
    owner: "{{ azerothcore_user }}"
    group: "{{ azerothcore_user }}"
  when: data_folder.stat.exists == false

- name: Extract map data
  unarchive:
    src: "{{ azerothcore_data_url }}/download/{{ azerothcore_data_version }}/data.zip"
    dest: "/home/{{ azerothcore_user }}/{{ azerothcore_folder }}/data/{{ azerothcore_data_version }}"
    remote_src: yes
  when: data_folder.stat.exists == false